name: mobile_ui
description: "Mobile UI for Software Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  fl_chart: ^0.41.0
  flutter_native_splash:
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  flutter_slidable: ^3.1.1
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/